#pragma once
enum ServerSyncho : int
{
    BAD = 1,
    REGISTRATION = 2,
    OKLOGIN = 3,
    BADLOGIN = 4,
    AUTORIZATION = 5,
    ADDFILE = 6,
    ADDFRIEND = 7,
    CHECKFRIENDANDFILE = 8,
    FRIENDSHIPSUCCESSFUL = 9,
    WAITINGFRIENDSHIP = 10,
    CHECKFRIENDANDFILESUCCESSFUL = 11,
    CHECKFRIENDANDFILEBAD = 12,
    OKREG = 13,
};

enum ServerFS : int
{
    CREATEFOLDER = 1,
    DELETEFILE = 2,
    SENDFILE = 3,
    DOWNLOADFILE = 4,
    OKSENDING = 5,
    OKDOWNLOAD = 6,
};
